### ISSUE TITLE
specs compiled for scala 2.8

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#100]
```
Please, compile specs for scala 2.8.
```

Original issue reported on code.google.com by `stepan.k...@gmail.com` on 28 Nov 2009 at 4:29

**Comment by GoogleCodeExporter** [comment]
```
Oh, found it on Downloads page.
```

Original comment by `stepan.k...@gmail.com` on 28 Nov 2009 at 4:29

**Comment by GoogleCodeExporter** [comment]
```
Is it downloadable from any Maven repository?
```

Original comment by `stepan.k...@gmail.com` on 28 Nov 2009 at 4:34

**Comment by GoogleCodeExporter** [comment]
```
1.6.1 is compiled against 2.7.

1.6.0-2.8.0 does not work with latest Scala 2.8.

So, requesting specs compiled againts 2.8 again.
```

Original comment by `stepan.k...@gmail.com` on 28 Nov 2009 at 4:46

**Comment by GoogleCodeExporter** [comment]
```
Hi Stepan,

I'm still working on it. I've tried a first version with 2.8.0.Beta1-RC1: 
http://nexus.scala-tools.org/content/repositories/releases/org/scala-
tools/testing/specs/1.6.1-2.8.0.Beta1-RC1/

but I still have a compiler crash when compiling with RC2.
```

Original comment by `etorrebo...@gmail.com` on 28 Nov 2009 at 11:43
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
The most recent version of specs for Scala 2.8.0 can be found here: 
http://nexus.scala-
tools.org/content/repositories/releases/org/scala-tools/testing/specs/1.6.1-
2.8.0.Beta1-RC2/
```

Original comment by `etorrebo...@gmail.com` on 10 Dec 2009 at 3:58
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I get exceptions when running with 2.8:

Exception in thread "main" java.lang.NoClassDefFoundError: scala/Iterable
    at org.jetbrains.plugins.scala.testingSupport.specs.SpecsRunner.main(SpecsRunner.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:110)
Caused by: java.lang.ClassNotFoundException: scala.Iterable
    at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
    at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
```

Original comment by `meme...@gmail.com` on 14 Dec 2009 at 9:45

**Comment by GoogleCodeExporter** [comment]
```
Can you please specify which exact versions of specs and scala you are using?

Thanks.
```

Original comment by `etorrebo...@gmail.com` on 15 Dec 2009 at 2:05

**Comment by GoogleCodeExporter** [comment]
```
I'm running:
 - specs  1.6.1-2.8.0.Beta1-RC2
 - scala: 2.8.0.Beta1-RC2
```

Original comment by `meme...@gmail.com` on 15 Dec 2009 at 10:44

**Comment by GoogleCodeExporter** [comment]
```
Hi, Sorry for the delay in my answer. I hadn't noticed this but it looks, from 
the 
stacktrace you sent that you're trying to run a specification using the specs 
support 
in IntelliJ. 

It seems that this IntelliJ "testingsupport" hasn't been upgraded to Scala 2.8 
and 
certainly not to the latest specs version.
```

Original comment by `etorrebo...@gmail.com` on 17 Dec 2009 at 7:45
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
```
Well, Intellij is definately 2.8 -- the plugin is built with 2.8 and I'm using 
2.8
and it supports all the 2.8 features. But it could be, like you say, that the
launcher is out of date. I'll ping Alexander. Thanks!
```

Original comment by `meme...@gmail.com` on 18 Dec 2009 at 5:01

**Comment by GoogleCodeExporter** [comment]
```
2.8.0 is just out. And I cannot find any spec on the repo that are compiled 
against it.

 error: error while loading Specification, Scala signature Specification has wrong version
[INFO]  expected: 5.0

```

Original comment by `coldbo...@gmail.com` on 20 Jul 2010 at 4:55

**Comment by GoogleCodeExporter** [comment]
```
Hi, the new version is here: 
http://scala-tools.org/repo-releases/org/scala-tools/testing/specs_2.8.0/1.6.5/
```

Original comment by `etorrebo...@gmail.com` on 20 Jul 2010 at 8:24
