### ISSUE TITLE
java.lang.NoSuchMethodError: scala.runtime.RichInt.to(I)Lscala/Range with Scala 2.7.0-rc1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#11]
```
What steps will reproduce the problem?

Execute a test in a JUnit4 runner with Scala 2.7.0-rc1.

What is the expected output? What do you see instead?

Test should run to completion. Instead the following happens:

java.lang.NoSuchMethodError: scala.runtime.RichInt.to(I)Lscala/Range;
        at
org.specs.runner.JUnit38SuiteRunner.makeDescription(JUnit38SuiteRunner.scala:52)
        at
org.specs.runner.JUnit38SuiteRunner.getDescription(JUnit38SuiteRunner.scala:37)

What version of the product are you using? On what operating system?
Specs 1.3.0-SNAPSHOT as of a few minutes ago and Scala 2.7.0-rc1. Note that
the latter is available from the scala-tools.org maven repo so should be
easy to test 

Please provide any additional information below.
I am not sure if this is a specs or scala bug, so please let me know if
it's the latter so that we can move it to the Scala tracker.
```

Original issue reported on code.google.com by `ismaelj` on 9 Feb 2008 at 2:06

**Comment by GoogleCodeExporter** [comment]
```
For some reason maven was still using specs 1.2.2 (it looked odd to me when I 
noticed
that JUnit38SuiteRunner showed in the stacktrace even though it has been 
removed). 

specs 1.3.0-SNAPSHOT doesn't actually have this problem, so feel free to close 
this.
(I would, but for some reason Google Code does not allow submitters to close 
their
own issues)
```

Original comment by `ismaelj` on 9 Feb 2008 at 2:42

**Comment by GoogleCodeExporter** [comment]
```
For now I have lots of compilation errors with 2.7.0-rc1. Most of them are 
related to
ScalaCheck, so I may have to ask Rickard Nillson to compile to 2.7.0 first!
```

Original comment by `etorrebo...@gmail.com` on 9 Feb 2008 at 2:54
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Interesting. I guess it doesn't affect me because I am not hitting those 
codepaths then.
```

Original comment by `ismaelj` on 9 Feb 2008 at 2:57

**Comment by GoogleCodeExporter** [comment]
```
I tried to compile my source code with Scala-2.7.0.rc1 tonight. I was able to 
solve
some issues but not those related to Scalacheck. 

And unfortunately I was not able to reproduce the error on a simple scala 
example
which could show an error in the compiler.

Still investigating,...
```

Original comment by `etorrebo...@gmail.com` on 13 Feb 2008 at 3:19

**Comment by GoogleCodeExporter** [comment]
```
For the record I found a couple of cases where the Scala compiler seems to be
rejecting valid code that worked in 2.6.1:

https://lampsvn.epfl.ch/trac/scala/ticket/456
https://lampsvn.epfl.ch/trac/scala/ticket/458
```

Original comment by `ismaelj` on 13 Feb 2008 at 9:55

**Comment by GoogleCodeExporter** [comment]
```
Yes case classes have been modified to allow inheritance AFAIK. This may have
introduced new issues.

I'll try to get a test case as you did as soon as I can.
```

Original comment by `etorrebo...@gmail.com` on 14 Feb 2008 at 1:52
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I have now recompiled specs ok with an unofficial version of Scalacheck also 
compiled
with Scala-2.7.0-rc2.

When ScalaCheck will release its new version, compatible with Scala 2.7.0 
final, I
will  also release the new specs version.

The modifications introduced for case classes indeed forbid 2.7.0 code to work 
with
2.6.1 code.

So let me close this for now and let's wait for the final release.
```

Original comment by `etorrebo...@gmail.com` on 17 Feb 2008 at 1:49
- Changed state: **Verified**
