### ISSUE TITLE
Use of doLast does not compile with Specs for Scala 2.8.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [etorreborre/specs#153]
```
*What steps will reproduce the problem?

Compile a simple Specs test like the following using Scala 2.8.0 and the latest 
Specs RC for Scala 2.8.0:

import org.specs._
object SpecsTest extends SpecificationWithJUnit {
    "Specs" should {
        "compile with doLast" in { }
        doLast { }
    }
}

*What is the expected output? What do you see instead?

I expect the test to compile and run successfully.  Instead, the Scala compiler 
outputs the following error:

SpecsTest.scala:6: error: overloaded method value should with alternatives:
  (a: => Unit)Unit <and>
  (a: org.specs.specification.PrefixedExamples)org.specs.specification.Sus <and>
  (a: => org.specs.specification.Examples)org.specs.specification.Sus
 cannot be applied to (Option[Unit])
    "Specs" should {
        ^
However, if I comment out the doLast line, it compiles fine.  Using doFirst 
also works fine.


*What version of the product are you using? On what operating system?

Running on Ubuntu with the following Maven dependencies:
<dependency>
    <groupId>org.scala-lang</groupId>
    <artifactId>scala-library</artifactId>
    <version>2.8.0.RC6</version>
</dependency>
<dependency>
    <groupId>org.scala-tools.testing</groupId>
    <artifactId>specs_2.8.0.RC7</artifactId>
    <version>1.6.5-SNAPSHOT</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.4</version>
    <scope>test</scope>
</dependency>

```

Original issue reported on code.google.com by `jbaldass...@gmail.com` on 3 Jul 2010 at 9:18

**Comment by GoogleCodeExporter** [comment]
```
I just noticed that the example works if I change it so that doLast appears 
before the test spec, like this:

"Specs" should {
    doLast { }
    "compile with doLast" in { }
}

Maybe the documentation 
(http://code.google.com/p/specs/wiki/DeclareSpecifications#Call_a_function_befor
e_or_after_each_example) is wrong because it gives the following example which 
won't compile (for me anyway):

"my system" should { 
  doFirst { prepareTheSystem() /** user-defined setup function */ }  
  // can also be written: prepareTheSystem().doFirst

  "execute this" in {...}
  "and that" in {...}

  doLast { cleanUp() /** user-defined cleanup function */ } 
  // can also be written: cleanUp().doLast
}

```

Original comment by `jbaldass...@gmail.com` on 3 Jul 2010 at 9:22

**Comment by GoogleCodeExporter** [comment]
```
Can you please try again with the latest snapshot? That should be fixed now.
```

Original comment by `etorrebo...@gmail.com` on 4 Jul 2010 at 2:11
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Yes, it works with the latest specs_2.8.0.RC7:1.6.5-SNAPSHOT.  Thanks.
```

Original comment by `jbaldass...@gmail.com` on 6 Jul 2010 at 2:10

**Comment by GoogleCodeExporter** [comment]
Original comment by `etorrebo...@gmail.com` on 6 Jul 2010 at 2:54
- Changed state: **Verified**
